openapi: 3.2.0
info:
  description: This API provides the IoT Accelerator SMS Messaging API.
  version: v2
  title: SMS Messaging Query SMS API
  x-audience: external-public
servers:
- url: https://sms.iot-api.aeris.com/dcpapi/smsmessaging/v1
  description: SMS API server
security:
- BasicAuth: []
tags:
- name: querySMS
paths:
  /outbound/{senderAddress}/requests/{requestId}/deliveryInfos:
    get:
      summary: Queries the delivery status of an SMS
      tags:
      - querySMS
      operationId: querySMS
      parameters:
      - name: senderAddress
        description: A string that represents the address of the enterprise that raises the request.For example tel:12345678
        in: path
        required: true
        schema:
          type: string
      - name: requestId
        description: A string that must be entered as returned in the related sendSMS successful response.
        in: path
        required: true
        schema:
          type: string
      - name: Authorization
        description: Should contain a base64 Basic auth string
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryInfoList'
              example:
                deliveryInfo:
                - address: tel:13500000991
                  deliveryStatus: DeliveredToTerminal
                - address: tel:13500000992
                  deliveryStatus: DeliveredToNetwork
                resourceURL: https://sms.iot-api.aeris.com/dcpapi/smsmessaging/v1/outbound/tel:12345/requests/dcp1234567/deliveryInfos
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
              example:
                requestError:
                  serviceException:
                    messageId: SVC0010
                    text: Requested information unavailable as the retention time interval has expired.
                    variables: ''
        '401':
          description: Authentication Failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
              example:
                requestError:
                  policyException:
                    messageId: POL0010
                    text: User has not been provisioned for %1
                    variables: SMSMessaging
        '404':
          description: No Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
components:
  schemas:
    DeliveryInfoList:
      type: object
      required:
      - deliveryInfo
      - resourceURL
      properties:
        deliveryInfo:
          type: array
          description: List of deliveryInfos
          items:
            $ref: '#/components/schemas/DeliveryInfo'
        resourceURL:
          type: string
          description: Link to the successful response.
    RequestError:
      type: object
      properties:
        requestError:
          type: object
          properties:
            serviceException:
              type: object
              properties:
                messageId:
                  type: string
                  description: violation identifier, ref. User Guide
                text:
                  type: string
                  description: describes the violation
                variables:
                  type: string
                  description: points to the variable(s) in violation
            policyException:
              type: object
              properties:
                messageId:
                  type: string
                  description: violation identifier, ref. User Guide
                text:
                  type: string
                  description: describes the violation
                variables:
                  type: string
                  description: points to the variable(s) in violation
    DeliveryInfo:
      type: object
      required:
      - address
      - deliveryStatus
      properties:
        address:
          type: string
          description: 'The recipients MSISDN including the tel: protocol identifier. For example: tel:16309700001'
        deliveryStatus:
          type: string
          description: 'Delivery status for the recipient identified by address. '
          enum:
          - DeliveredToTerminal
          - DeliveryUncertain
          - DeliveryImpossible
          - MessageWaiting
          - DeliveredToNetwork
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
